name: CI(macos)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.2.0
      with:
        channel: 'stable'
    - name: Upload Windows Build
      uses: actions/upload-artifact@1.0.0
      with:
        name: windows-build
        path: build/windows
    - run: flutter channel master
    - run: flutter upgrade
    - run: flutter pub get
    - run: flutter config --enable-windows-desktop 
    - run: flutter build windows
  build_ios:
    name: Build iOS
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.2.0
      with:
        channel: 'stable'
    - name: Upload iOS Build
      uses: actions/upload-artifact@1.0.0
      with:
        name: ios-build
        path: build/ios/iphoneos
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
  
